### ISSUE TITLE
리눅스에서 Mecab 실행시 mecab-ko-dic을 가져오지 못하는 에러

### ISSUE THREAD

**Issue by Sain-Tech** [refind-opensw/refind-web_history#10]
리눅스 터미널로 python3 실행 후
```
>>> from eunjeon import Mecab
>>> mecab = Mecab()
```
를 수행하면 다음과 같은 에러가 발생합니다.
```
Traceback (most recent call last):
  File "/home/server-sn/.local/lib/python3.6/site-packages/eunjeon/_mecab.py", line 101, in __init__
    self.tagger = Tagger('--rcfile %s' % dicpath)
  File "/home/server-sn/.local/lib/python3.6/site-packages/eunjeon/mecab.py", line 528, in __init__
    this = _MeCab.new_Tagger(*args)
RuntimeError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/server-sn/.local/lib/python3.6/site-packages/eunjeon/_mecab.py", line 104, in __init__
    self.tagger = Tagger('--rcfile %s' % dicpath)
  File "/home/server-sn/.local/lib/python3.6/site-packages/eunjeon/mecab.py", line 528, in __init__
    this = _MeCab.new_Tagger(*args)
RuntimeError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/server-sn/.local/lib/python3.6/site-packages/eunjeon/_mecab.py", line 106, in __init__
    raise Exception('The MeCab dictionary does not exist at "%s". Is the dictionary correctly installed?\nYou can also try entering the dictionary path when initializing the Mecab class: "Mecab(\'/some/dic/path\')"' % dicpath)
Exception: The MeCab dictionary does not exist at "/home/server-sn/.local/lib/python3.6/site-packages/eunjeon/data/mecabrc". Is the dictionary correctly installed?
You can also try entering the dictionary path when initializing the Mecab class: "Mecab('/some/dic/path')"
```

해결책으로 다운받은 mecab-ko-dic 안의 모든 내용물을 pyscripts 폴더 내로 옮기고,

url_wordfreq_seeker.py : 113번째 줄의

`mecab = Mecab()` 

을

`mecab = Mecab("/usr/local/lib/mecab/dic/mecab-ko-dic/")`

@rhgo1749 병합 진행할테니, 받으신 후 테스트 진행 부탁드리겠습니다.

로 변경하여, mecab-ko-dic 에 대한 경로를 직접 지정하였습니다.

**Comment by Sain-Tech** [comment]
정정합니다.

노드로 실행 시 문제가 있어서, pyscript에 있던 mecab-ko-dic 파일들을

서버 기본 디렉토리로 이동하였습니다.
